# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A function helps to get terms using Rcpp
#' @description A function helps to get terms using Rcpp
#' @param x the word in one document
#' @param vocab the all word list
#' @return a index
#' 
#' @export
get_termsC <- function(x, vocab) {
    .Call('_StatComp22019_get_termsC', PACKAGE = 'StatComp22019', x, vocab)
}

